services:
  web:
    build: .
    entrypoint: ["uvicorn", "src.server:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "3000:8000"
    volumes:
      - .:/app
      - ~/.config/gcloud:/root/.config/gcloud:ro
    env_file:
      - .env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/root/.config/gcloud/application_default_credentials.json

  app:
    build: .
    volumes:
      - .:/app
      - ~/.config/gcloud:/root/.config/gcloud:ro
    env_file:
      - .env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/root/.config/gcloud/application_default_credentials.json

  test:
    build: .
    entrypoint: pytest
    volumes:
      - .:/app
      - ~/.config/gcloud:/root/.config/gcloud:ro
    env_file:
      - .env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/root/.config/gcloud/application_default_credentials.json
